# /home/lvchen/body_SB3/configs/body_walk_evaluate_config.yaml

env_id: myoLegWalk-v0
# model: /home/lvchen/body_SB3/logs/walkenv/models/eval_x/best_model.zip
# model: /home/lvchen/body_exo_SB3/best_human_model.zip
model: "/home/lvchen/body_SB3/logs/joint_human/best_model.zip"
vecnorm: ""                 # 可选：VecNormalize pkl 路径

n_eval: 1
seed: 4
deterministic: true
max_steps: 0                # 0 表示使用 env 默认 episode 长度

# 输出目录
out_dir: /home/lvchen/body_SB3/logs/walkenv/eval/best_10_auto

# 视频
record_video: true
video_dir: /home/lvchen/body_SB3/logs/walkenv/eval/videos 
video_length: 2000

# speed 分布 histogram（可选，文件会变大）
save_speed_hist: false
speed_hist_bins: 50
